#
# Python modules below are needed to run example notebook scripts
#
name: rte_examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.15
  - urllib
  - pooch
  - pyrte_rrtmgp >=0.2.5
  - netcdf4
  - metpy
  